[env]
_.file = '.env'

[tools]
nodejs = "20.14.0"
pnpm = "9.8.0"
opentofu = "1.8.0"
terragrunt = "0.63.6"
helm = "3.15.4"

[plugins]
pnpm = "https://github.com/jonathanmorley/asdf-pnpm.git"
opentofu = "https://github.com/virtualroot/asdf-opentofu.git"
terragrunt = "https://github.com/ohmer/asdf-terragrunt.git"
helm = "https://github.com/Antiarchitect/asdf-helm.git"

[settings]
task_output = "Storm Chef: "
paranoid = false
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
legacy_version_file = true
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '1 week'
verbose = false
asdf_compat = false
http_timeout = 30
jobs = 4
raw = false
yes = true
not_found_auto_install = true

[tasks."sign:commit"]
run = "gitsign verify --certificate-identity=patrick.joseph.sullivan@protonmail.com --certificate-oidc-issuer=https://accounts.google.com HEAD"
